[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wzrd"
version = "0.1.0"
description = "A command line tool to generate Python scripts using LLM"
authors = [{name = "Your Name", email = "your.email@example.com"}]
requires-python = ">=3.11"

[project.dependencies]
llm = "^0.2.0"
pydoc = "*"
